name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
      - 'presentation/**'
      - 'paper/**'

jobs:
  publish:
    name: Build & Deploy Quarto Projects
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        QUARTO_DIR:
          - presentation
          - paper
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install tinytex
        run: quarto install tinytex
        shell: bash

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash
        working-directory: ${{ matrix.QUARTO_DIR }}

      - name: Publish ${{ matrix.QUARTO_DIR }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.QUARTO_DIR }}/_site
          destination_dir: ${{ matrix.QUARTO_DIR }}
          keep_files: true

  index:
    name: Index page
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Publish index page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontpage
          keep_files: true
